#!/usr/bin/env python3
"""Generate admin_credentials.toml with a bcrypt password hash and random cookie key."""

from __future__ import annotations

import getpass
import secrets
from pathlib import Path

import bcrypt

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "admin_credentials.toml"
SAMPLE = ROOT / "admin_credentials.sample.toml"


def main() -> None:
    if OUTPUT.exists():
        answer = input(f"{OUTPUT.name} already exists. Overwrite? [y/N]: ").strip().lower()
        if answer != "y":
            print("Aborted.")
            return

    username = input("Admin username [admin]: ").strip() or "admin"
    name = input("Display name [Church Admin]: ").strip() or "Church Admin"
    email = input("Email [admin@example.com]: ").strip() or "admin@example.com"

    while True:
        password = getpass.getpass("Password: ")
        confirm = getpass.getpass("Confirm password: ")
        if password and password == confirm:
            break
        print("Passwords do not match or are empty. Try again.")

    password_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt(12)).decode()
    cookie_key = secrets.token_urlsafe(32)

    content = f"""# Generated by scripts/setup_admin.py — keep this file private.

[credentials.usernames.{username}]
email = "{email}"
name = "{name}"
password = "{password_hash}"

[cookie]
expiry_days = 1
key = "{cookie_key}"
name = "church_directory_cookie"
"""
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    print("Restart the app to use the new credentials.")


if __name__ == "__main__":
    main()
