#!/usr/bin/env python3
"""Generate admin_credentials.toml for email + password + OTP login."""

from __future__ import annotations

import getpass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "admin_credentials.toml"


def main() -> None:
    if OUTPUT.exists():
        answer = input(f"{OUTPUT.name} already exists. Overwrite? [y/N]: ").strip().lower()
        if answer != "y":
            print("Aborted.")
            return

    email1 = input("Allowlisted email 1: ").strip()
    email2 = input("Allowlisted email 2: ").strip()
    email3 = input("Allowlisted email 3 (Gmail sender): ").strip() or "dvjgenis@gmail.com"

    while True:
        password = getpass.getpass("Shared staff password: ")
        confirm = getpass.getpass("Confirm password: ")
        if password and password == confirm:
            break
        print("Passwords do not match or are empty. Try again.")

    app_password = getpass.getpass("Gmail App Password (16 chars, spaces ok): ").strip()

    content = f"""# Generated by scripts/setup_admin.py — keep this file private.

[credentials.usernames.filpilchurch]
email1 = "{email1}"
email2 = "{email2}"
email3 = "{email3}"
password = "{password}"

[smtp]
user = "{email3}"
app_password = "{app_password}"
"""
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    print("Restart the app to use the new credentials.")


if __name__ == "__main__":
    main()
